plugins:
 - rubocop-rake
 - rubocop-rspec

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
